output_dir: 'experiments/output'
log_dir: 'experiments/log'
device: 'cpu'
dataset:
  name: 'dsoft'
  root: 'data/dsoft'
  augmentation:
    horizontal_flip: True
    rotation: 30
  mean: [0.5,0.5,0.5]
  sigma: [0.5,0.5,0.5]
  train_set: 'train.csv'
  test_set: 'test.csv'
model:
  base: 'mobilenet_v2'
  pretrained: True
  num_output: 1
  image_size: [224,224]
train:
  batch_size: 24
  optimizer: 'adam'
  lr: 0.001
  num_epochs: 10
test:
  batch_size: 24